### ISSUE TITLE
Integrate OpenTok + ReplayKit 

### ISSUE THREAD

**Issue by WermesRodrigues** [AndreiMisiukevich/OpenTok-Xamarin.Forms#10]
Hi Andrei,

There is a feature very important and I think will be helpful for many people the integration of SDK with ReplayKit from Apple to share the screen.

The user will be able to share the screen of the App and navigate between other screen.

Is there one way to share the screen using the OpenTok?

Many Thanks.

**Comment by AndreiMisiukevich** [comment]
Hi, don't think so
OpenTok is just library for video/audio calls and text messaging
