### ISSUE TITLE
Audio control?

### ISSUE THREAD

**Issue by GorkaL** [AndreiMisiukevich/OpenTok-Xamarin.Forms#11]
Hi, is there any option to control the audio volume?

**Comment by AndreiMisiukevich** [comment]
Need to check it

**Comment by AndreiMisiukevich** [comment]
didn't find how to achieve it

@alexsorokoletov, sorry for disturbing. Is it possible to control the volume of subscribers? I found only JS related info...
Thanks!

**Comment by alexsorokoletov** [comment]
@AndreiMisiukevich I don’t recall off top of my head - if it is possible with iOS or Android SDK then possible with Xamarin SDK. 
Sorry for the redirection instead of answer.

**Comment by AndreiMisiukevich** [comment]
@alexsorokoletov thank you for your answer!
I haven't found anything related to audio controlling in the docs.

@GorkaL if you find some info about how to control audion in tokBox docs, let me know, I'll implement this feature
