### ISSUE TITLE
Video Decoder Error

### ISSUE THREAD

**Issue by JojoDuke** [AndreiMisiukevich/OpenTok-Xamarin.Forms#12]
Hello, I've followed all steps and looked at the sample code but any time I try running on a physical device I get this same error.
`Severity	Code	Description	Project	File	Line	Suppression State
Error		java/lang/String;)Lorg/webrtc/VideoDecoder;: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoDecoderFactory.createDecoder : (Ljava/lang/String;)Lorg/webrtc/VideoDecoder;	VoiceChatTest.Android			
`

Im very sure that my SDK is greater than 24, is there a solution to this?

**Comment by AndreiMisiukevich** [comment]
@JojoDuke show me your manifest file

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/67664492-c94a6b00-f978-11e9-9810-fe2bc85d7b47.png)

this should be 24
