### ISSUE TITLE
Mute and unmute video as well as audio

### ISSUE THREAD

**Issue by mthirukavi** [AndreiMisiukevich/OpenTok-Xamarin.Forms#13]
Hi,
I'm trying to implement a video chat application, i have to add the feature to mute and unmute audio as well video. How can I do it with it. Thanks in advance.

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/72803589-850cf500-3c5f-11ea-8a46-f49c07345f04.png)
