### ISSUE TITLE
Publisher view hides when subscriber video is loaded

### ISSUE THREAD

**Issue by mthirukavi** [AndreiMisiukevich/OpenTok-Xamarin.Forms#14]
Hi,
 When I change the view of the ChatRoomPage.xaml, the publisher view is getting hidden once subscriber stream is loaded. how can I fix it? 

Thanks.

**Comment by AndreiMisiukevich** [comment]
How did you change it? And what is your issue? provide xaml / video.
I cannot reproduce it on my sample

**Comment by mthirukavi** [comment]
```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:tok="clr-namespace:Xamarin.Forms.OpenTok;assembly=Xamarin.Forms.OpenTok"
             xmlns:tokService="clr-namespace:Xamarin.Forms.OpenTok.Service;assembly=Xamarin.Forms.OpenTok" x:Class="247.Views.VideoCall"
             xmlns:ios = "clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"   >
    <ContentPage.Content>
        <AbsoluteLayout BackgroundColor="#ffffff">
            <StackLayout AbsoluteLayout.LayoutBounds="0,0.1,1,1"
                         AbsoluteLayout.LayoutFlags="All" 
                         BindableLayout.ItemsSource="{Binding Path=StreamIdCollection, Source={x:Static tokService:CrossOpenTok.Current}}">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <StackLayout>
                            <tok:OpenTokSubscriberView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
                        StreamId="{Binding .}"/>
                        </StackLayout>
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </StackLayout>
            <tok:OpenTokPublisherView AbsoluteLayout.LayoutBounds="0,0.9,0.2,0.2" BackgroundColor="Aquamarine" AbsoluteLayout.LayoutFlags="All"   x:Name="publisherVideo" />
            <Image Source="end.png" AbsoluteLayout.LayoutBounds="1,1,1,0.4" HeightRequest="150" AbsoluteLayout.LayoutFlags="All" HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand" >
                <Image.GestureRecognizers>
                    <TapGestureRecognizer Tapped="OnEndCall" NumberOfTapsRequired="1">

                    </TapGestureRecognizer>
                </Image.GestureRecognizers>
            </Image>
             </AbsoluteLayout>
                </ContentPage.Content>
</ContentPage>
```

**Comment by AndreiMisiukevich** [comment]
why did you add it twice?

```xaml
            <StackLayout AbsoluteLayout.LayoutBounds="0,0.1,1,1"
                         AbsoluteLayout.LayoutFlags="All" 
                         BindableLayout.ItemsSource="{Binding Path=StreamIdCollection, Source={x:Static tokService:CrossOpenTok.Current}}">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <StackLayout>
                            <tok:OpenTokSubscriberView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
                        StreamId="{Binding .}"/>
                        </StackLayout>
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </StackLayout>
```

**Comment by AndreiMisiukevich** [comment]
Anyway, it's not an issue of this library (if it works on my sample). Fix your layout.

**Comment by mthirukavi** [comment]
> why did you add it twice?
> 
> ```
>             <StackLayout AbsoluteLayout.LayoutBounds="0,0.1,1,1"
>                          AbsoluteLayout.LayoutFlags="All" 
>                          BindableLayout.ItemsSource="{Binding Path=StreamIdCollection, Source={x:Static tokService:CrossOpenTok.Current}}">
>                 <BindableLayout.ItemTemplate>
>                     <DataTemplate>
>                         <StackLayout>
>                             <tok:OpenTokSubscriberView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
>                         StreamId="{Binding .}"/>
>                         </StackLayout>
>                     </DataTemplate>
>                 </BindableLayout.ItemTemplate>
>             </StackLayout>
> ```

It was there one time only in my code, i pasted twice here. 

The publisherview in overlayed by subscriberview. I mean the publisherview is under subscriberview. so i cant view the publisher profile.

**Comment by AndreiMisiukevich** [comment]
I got it, but it's not an issue related to this library. Something is wrong with absolute layout

**Comment by mthirukavi** [comment]
ok. Thanks. Its really a great work what you have done.

**Comment by rgustavsson** [comment]
@mthirukavi did you manage to get around it? I know it is not an issue with this lib but I am having the same issue..

**Comment by mthirukavi** [comment]
@rgustavsson Nope... But it's working fine in iOS devices, the problem is only with Android devices. Working on it. Once got it, will update here.

**Comment by almirtavares** [comment]
Hi guys.... I have the same problem: Publisher view hides when subscriber video is loaded.

**Comment by AndreiMisiukevich** [comment]
v 1.2.1 !!!
