### ISSUE TITLE
got an error when build project

### ISSUE THREAD

**Issue by kldp** [AndreiMisiukevich/OpenTok-Xamarin.Forms#15]
java.lang.IllegalArgumentException: already added :  Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;

please help...

**Comment by AndreiMisiukevich** [comment]
Hi, @kldp have you resolved this issue?

**Comment by AndreiMisiukevich** [comment]
It seems to be a Xamarin issue https://www.google.com/search?sxsrf=ACYBGNRVGkwm_gb5-kRT_wsGc0bCgrORVQ%3A1579768564241&ei=9FopXsyuDrqDk74PsdyzsAs&q=xamarin+%22Lcom%2Fgoogle%2Fdevtools%2Fbuild%2Fandroid%2Fdesugar%2Fruntime%2FThrowableExtension%22&oq=xamarin+%22Lcom%2Fgoogle%2Fdevtools%2Fbuild%2Fandroid%2Fdesugar%2Fruntime%2FThrowableExtension%22&gs_l=psy-ab.3...317.1561..1698...0.0..0.115.1044.4j6......0....1..gws-wiz.......35i302i39.94APKJBpjo4&ved=0ahUKEwjM-OTAqJnnAhW6wcQBHTHuDLYQ4dUDCAs&uact=5

**Comment by kldp** [comment]
Yes, it is Xamarin issue, but not find any solution yet..Thanks for look in to that
