### ISSUE TITLE
Publisher view hides when subscriber video is loaded using AbsoluteLayout

### ISSUE THREAD

**Issue by almirtavares** [AndreiMisiukevich/OpenTok-Xamarin.Forms#17]
When I use at least one of the two views (Publisher or Subscriber) inside the AbsoluteLayout, the publisher view is getting hidden once subscriber stream is loaded. Is there a workaround from Lib about that?

**Comment by AndreiMisiukevich** [comment]
Hi, I heard about this issue.

what will happen if you wrap your views with additional ContentView?

**Comment by almirtavares** [comment]
- "what will happen if you wrap your views with additional ContentView?"

Subscriber overrides all other elements.

**Comment by almirtavares** [comment]
We are testing XAML is shown below:

<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:tok="clr-namespace:Xamarin.Forms.OpenTok;assembly=Xamarin.Forms.OpenTok"
             mc:Ignorable="d" x:Class="OpenTokExemplo.MainPage">

    <ContentPage.Content>

        <AbsoluteLayout x:Name="absoluteLayoutName">

            <tok:OpenTokSubscriberView x:Name="subscriberViewName" AbsoluteLayout.LayoutFlags="PositionProportional"
                                       AbsoluteLayout.LayoutBounds=".05,.80,80,140" />

            <tok:OpenTokPublisherView x:Name="publisherViewName" AbsoluteLayout.LayoutFlags="PositionProportional"  
                                      AbsoluteLayout.LayoutBounds=".05,.95,80,140" />

            <ImageButton Source="alternarCamera.png" Padding="10"
                BackgroundColor="#1787FB"
                CornerRadius="50"
                Clicked="OnSwapCamera"
                AbsoluteLayout.LayoutFlags="PositionProportional"  
                AbsoluteLayout.LayoutBounds=".95,.80,60,60" />

            <ImageButton Source="finalizarChamada.png" Padding="10"                   
                BackgroundColor="#E23C3C"             
                CornerRadius="50"
                Clicked="OnEndCall"
                AbsoluteLayout.LayoutFlags="PositionProportional"  
                AbsoluteLayout.LayoutBounds=".95,.95,60,60" />

        </AbsoluteLayout>

    </ContentPage.Content>
</ContentPage>

**Comment by AndreiMisiukevich** [comment]
Both iOS and Android?

**Comment by almirtavares** [comment]
We have not tested it on iOS yet, just Android.

**Comment by almirtavares** [comment]
SubscriberView and PublisherView Layers are loaded in the right order on the screen. When the video reception begins, SubscriberView overrides on the PublisherView.

Is there any way I can configure PublisherView to start after SubscriberView starts?

I think that changing the order of the initializations may solve it.

**Comment by AndreiMisiukevich** [comment]
```csharp
[assembly: ExportRenderer(typeof(OpenTokPublisherView), typeof(CustomOpenTokPublisherViewRenderer))]
namespace YOUR_NAME_SCPACE
{
    [Preserve(AllMembers = true)]
    public class CustomOpenTokPublisherViewRenderer : OpenTokPublisherViewRenderer
    {
        public OpenTokPublisherViewRenderer(Context context) : base(context)
        {
        }

        protected override void SubscribeResetControl() {
            base.SubscribeResetControl();
            PlatformOpenTokService.Instance.SubscriberUpdated += OnFixOrderingIssue;
        } 

        protected override void UnsubscribeResetControl() {
            base.UnsubscribeResetControl();
            PlatformOpenTokService.Instance.SubscriberUpdated -= OnFixOrderingIssue;
        }

        private async void OnFixOrderingIssue() {
            await Task.Delay(200);
            Device.BeginInvokeInMainThread(() => {
                if(Control == null)
                {
                    return;
                }
                Control.RemoveFromParent();
                SetNativeControl(Control);
            })
        }
    }
}
```

Try this renderer (make sure it is called)

**Comment by AndreiMisiukevich** [comment]
Did it help?

**Comment by AndreiMisiukevich** [comment]
Or wait a sec. Seems I found a solution

**Comment by AndreiMisiukevich** [comment]
1.2.1

**Comment by almirtavares** [comment]
I still have not been able to test the renderer you gave. We are testing some alternatives and have a short schedule for the development of the project.

**Comment by almirtavares** [comment]
Thanks for the contribution and release 1.2.1.
