### ISSUE TITLE
Ring feature.

### ISSUE THREAD

**Issue by mthirukavi** [AndreiMisiukevich/OpenTok-Xamarin.Forms#19]
Hi @AndreiMisiukevich,
   how to implement ring feature using this library?

**Comment by AndreiMisiukevich** [comment]
Open solution, configure the app with your keys and run sample.

**Comment by mthirukavi** [comment]
Yes, It's working fine. We designed it like Webex to join the session. Now we have to do it like WhatsApp Call. When the publisher clicks a button subscriber has to receive the call. There he can accept the call or reject it. Once rejected should notify the publisher.

**Comment by AndreiMisiukevich** [comment]
There is https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Lib/Xamarin.Forms.OpenTok/Service/IOpenTokService.cs#L10

it's an observable collection of current subscribers. If it changes, it means that somebody is joined or exited.

**Comment by AbuMandour** [comment]
Do this work when app is killed ?

**Comment by AndreiMisiukevich** [comment]
No idea, not sure
