### ISSUE TITLE
App store publish error

### ISSUE THREAD

**Issue by mthirukavi** [AndreiMisiukevich/OpenTok-Xamarin.Forms#20]
After development, I submitted the App to AppStore, I received the following mail. In our code, we don't use any WebView APIs. Is this the problem with your library.

**ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020.**

If yes, can you kindly let us know the alternate?

Thanks,
MTK.

**Comment by AndreiMisiukevich** [comment]
Hi, of course, this problem is not with my library.
This problem is related to Xamarin.Forms
https://github.com/xamarin/Xamarin.Forms/issues/7323
