### ISSUE TITLE
Nothing happens when selecting "Click to Chat"

### ISSUE THREAD

**Issue by kcp210** [AndreiMisiukevich/OpenTok-Xamarin.Forms#21]
I downloaded this repo and hardcoded keys in App.cs. When I run the project on iOS and Android, nothing is happening when I click the click to chat button. On Android, it does ask for permissions, but I cannot get the ChatRoomPage to push.

**Comment by AndreiMisiukevich** [comment]
Did you add permissions to manifest https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms ?

**Comment by AndreiMisiukevich** [comment]
Did you add CrossCurrentActivity.Current.Activity = this; // Add this line ?

**Comment by AndreiMisiukevich** [comment]
PlatformOpenTokService.Init();

**Comment by AndreiMisiukevich** [comment]
Or you using my sample?

Weird, it should work. Can you confirm that keys are not overridden somehow

**Comment by kcp210** [comment]
Thank you for your quick response. I was using your sample, but the keys were getting overwritten after I set them. All works now. Thank you!
