### ISSUE TITLE
Multi party and create session?

### ISSUE THREAD

**Issue by PeraDev7** [AndreiMisiukevich/OpenTok-Xamarin.Forms#22]
Anyone can help me? I need how to build the "create session" section like on web.
Thanks

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Xamarin.Forms.OpenTok.Sample/ChatRoomPage.xaml

**Comment by PeraDev7** [comment]
can i use with Android?

**Comment by AndreiMisiukevich** [comment]
yes


*Andrei Misiukevich*

*Lead Software Engineer at ISsoft Solutions*



*mobile: *+375 29 <+375%2017%20389%200100>303 40 07   Email:
andrei.misiukevich@gmail.com Skype: csi.andreymisyukevich

*Minsk,* *Belarus *(GMT+3)

**Comment by PeraDev7** [comment]
how? Sorry i'm new in xamarin

**Comment by AndreiMisiukevich** [comment]
https://www.vonage.com/communications-apis/video/

then download sample, setup keys and run

**Comment by PeraDev7** [comment]
i have the keys, i cannot run the .form project, but only android :(

**Comment by AndreiMisiukevich** [comment]
you should run android project

**Comment by AndreiMisiukevich** [comment]
Xamarin.Forms.OpenTok.Sample.Android

**Comment by PeraDev7** [comment]
can you write me on skype? https://join.skype.com/invite/hnNTVKvwuj4U

**Comment by AndreiMisiukevich** [comment]
remove this code and put your keys there
https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Xamarin.Forms.OpenTok.Sample/App.cs#L16-L33

**Comment by PeraDev7** [comment]
i need the option to create session, if possibile

**Comment by PeraDev7** [comment]
can you write me on skype?
