### ISSUE TITLE
How to multi party?

### ISSUE THREAD

**Issue by PeraDev7** [AndreiMisiukevich/OpenTok-Xamarin.Forms#23]
Can i use the multi party feature in xamarin? How?

**Comment by AndreiMisiukevich** [comment]
Xamarin.Forms
Here is the xaml of chat page for several participants: https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Xamarin.Forms.OpenTok.Sample/ChatRoomPage.xaml

Setup keys and run the sample from 3 devices e.g.

**Comment by PeraDev7** [comment]
Can i contact you? I can pay you.. i need some customizations

**Comment by AndreiMisiukevich** [comment]
@PeraDev7 can you show what do you want to achieve?
