### ISSUE TITLE
White screen on iphone

### ISSUE THREAD

**Issue by pbalbino** [AndreiMisiukevich/OpenTok-Xamarin.Forms#25]
It is not showing the video of what is being filmed on the iphone screen (iphone 6s iOS 13.4). Android is correct, I was the one who requested the focus recently. Now I went to test on the iphone and I couldn't, follow my xaml.

Note: In the app that receives the video it is possible to see the transmission, both in the front and back cameras, but on the screen itself is all white.
![IMG_20200420_165444373](https://user-images.githubusercontent.com/25305220/79794141-258ab800-8328-11ea-82a4-0bdc3fb9f74a.jpg)
[xaml.txt](https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/files/4505854/xaml.txt)

**Comment by AndreiMisiukevich** [comment]
Can you try to run my sample (on github) with your keys
Does it work for you?

Maybe it's layout issue

**Comment by AndreiMisiukevich** [comment]
```<tok:OpenTokPublisherView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="LightGray"/>```

But We don't see "LightGray" at all.

**Comment by pbalbino** [comment]
> `<tok:OpenTokPublisherView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="LightGray"/>`
> 
> But We don't see "LightGray" at all.

I removed it, it was just to visualize the location, but even so the screen remains white.

**Comment by pbalbino** [comment]
> Can you try to run my sample (on github) with your keys
> Does it work for you?
> 
> Maybe it's layout issue

Sorry for my lack of knowledge, but to install your test app on the iphone will I have to provision profile too?

**Comment by AndreiMisiukevich** [comment]
> > Can you try to run my sample (on github) with your keys
> > Does it work for you?
> > Maybe it's layout issue
> 
> Sorry for my lack of knowledge, but to install your test app on the iphone will I have to provision profile too?

You can try from simulator for example)
Or just set app bundle to your app's bundle.

**Comment by pbalbino** [comment]
I did a little test and removed the control from RelativeLayout:

    <StackLayout IsVisible="{Binding StageVisibility, Converter={StaticResource VisibilityVistoriaRemotaConverter}, ConverterParameter=1}" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                    <tok:OpenTokPublisherView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>
                    
                </StackLayout>`

Now the video appears, but it is not what I need. Looking at my complete shaman I gave you, do you see something wrong?

**Comment by AndreiMisiukevich** [comment]
I see that you didn't add any constraints to relative layout children. I presume this is the problem.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/relative-layout
