### ISSUE TITLE
Android Issue

### ISSUE THREAD

**Issue by gastonagusti** [AndreiMisiukevich/OpenTok-Xamarin.Forms#26]
Hi, i have a problem whit Xamarin Android Implementation. 

![sdkproblem](https://user-images.githubusercontent.com/52378820/80130190-991e0680-856e-11ea-9f6f-4efe6f0d4cff.png)

is there a solution to this?

**Comment by AndreiMisiukevich** [comment]
Try to build my sample project
It works for me even with 21 min version

**Comment by AndreiMisiukevich** [comment]
Also check this 
![image](https://user-images.githubusercontent.com/10124814/80131234-9937f980-85a2-11ea-989f-5b5902a23ed2.png)


Probably you need remove all bin/obj folders. Clean and rebuild

**Comment by gastonagusti** [comment]
Hi, thanks for the reply! try that solution but it doesn't work =(

**Comment by AndreiMisiukevich** [comment]
> Hi, thanks for the reply! try that solution but it doesn't work =(

Did you try to build my sample?

**Comment by AndreiMisiukevich** [comment]
https://stackoverflow.com/questions/57027952/xamarin-build-error-defining-a-default-interface-method-requires-min-sdk-vers

**Comment by AndreiMisiukevich** [comment]
You can follow steps provided there https://github.com/Baseflow/XamarinMediaManager/issues/526

**Comment by AndreiMisiukevich** [comment]
Important

![image](https://user-images.githubusercontent.com/10124814/80310244-56fcfb00-87e2-11ea-9a60-c62e4eb16aeb.png)
