### ISSUE TITLE
Remove_popup

### ISSUE THREAD

**Issue by kldp** [AndreiMisiukevich/OpenTok-Xamarin.Forms#27]
Hi,
When we start chat, there is a popup which  populated by default over the screen. user have to close it then we can see other user video. can we remove/close it automatically? or there is any mechanism to not show the popup by default?
Please suggest me if it is possible. Thanks

**Comment by AndreiMisiukevich** [comment]
Hi, what the popup is? Can you attach a screenshot?

**Comment by AndreiMisiukevich** [comment]
I presume that's permission requesting alert. And of course, it's impossible to skip it

**Comment by kldp** [comment]
yes, that was permission requesting alert, and can't skip. thanks
