### ISSUE TITLE
Opentok Pre-Call test

### ISSUE THREAD

**Issue by Mibuw** [AndreiMisiukevich/OpenTok-Xamarin.Forms#28]
Hi Andrei, is there any possibility to include a pre-call test to check the connection upfront?!
I saw samples in javascript and native ios and android but nothing in xamarin so far.

Regards - Wolfgang

**Comment by AndreiMisiukevich** [comment]
Hi, feel free to make PR with this feature. I don't know how to implement it :)

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/Xamarin.Forms.Vonage
