### ISSUE TITLE
Subscriber video paused- show message to publisher.

### ISSUE THREAD

**Issue by mthirukavi** [AndreiMisiukevich/OpenTok-Xamarin.Forms#29]
Hi Friend,
   I want to show a message to publisher as "Video paused by other party" when subscriber pauses the video. How to achieve it?

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Lib/Xamarin.Forms.OpenTok/OpenTokView.cs#L9

All opentok views have property for determining if the video is running (So, just observe this property)
