### ISSUE TITLE
Text messages / Signaling

### ISSUE THREAD

**Issue by AndreiMisiukevich** [AndreiMisiukevich/OpenTok-Xamarin.Forms#3]
https://tokbox.com/developer/tutorials/android/text-chat/

**Comment by Mibuw** [comment]
Is this signaling api already part of Xamarin.Opentok.Android? It would be a great addition.

**Comment by AndreiMisiukevich** [comment]
@Mibuw seems yes :)
So, going to make awesome XF sdk-wrapper for that :)

**Comment by AndreiMisiukevich** [comment]
Pushed code
So, i think, i will make release on this week

**Comment by Mibuw** [comment]
Looks very promising, thanks a lot!

**Comment by AndreiMisiukevich** [comment]
video is coming soon :)
