### ISSUE TITLE
Remove binding to StreamIdCollection() from one Page and bind it again on another Page automatically on Android

### ISSUE THREAD

**Issue by alirazamsp** [AndreiMisiukevich/OpenTok-Xamarin.Forms#30]
I have first screen in which I have one publisher and subscriber view which works great. I navigate to next screen by PushModelAsync and I have a ListView in next screen. I have a subcriberView in the ItemTemplate of the listview which is binded to StreamIdCollection.

When I launch app, i see first screen and i can see publisher and subscriber. I go to see participants on the next screen. It works. I come back and go again to see the participants but app crashes with following exception:

`{System.MissingMethodException: No constructor found for http://Xamarin.Forms.OpenTok.Android.OpenTokSubscriberViewRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationE…}`

I tried to add such a constructor but ViewRenderer does not have a constructor which takes these two arguments. It only takes one argument (Context).

iOS is working fine. Problem is only with Android. In iOS, upon navigating back to first screen, SubscriberView automatically binds to StreamIdCollection property but does not.

**Comment by AndreiMisiukevich** [comment]
Hi, it looks like Xamarin.Forms bug.

**Comment by alirazamsp** [comment]
I will manage this by calling EndSession() and TryStartSession() upon navigating back to first page from second(Participants) Page.

**Comment by AndreiMisiukevich** [comment]
very similar https://github.com/xamarin/Xamarin.Forms/issues/5911

**Comment by AndreiMisiukevich** [comment]
try 1.2.5 (it will become available in 20 mins) and let me know
