### ISSUE TITLE
Is there any way to get Audio Levels Information in Xamarin Forms ? 

### ISSUE THREAD

**Issue by alirazamsp** [AndreiMisiukevich/OpenTok-Xamarin.Forms#31]
If you refer to this documentation page on TokBox site: 
[https://tokbox.com/developer/guides/customize-ui/android/index.html#audio_levels](url)

They have a method for android to get Audio Levels information for each subscriber and publisher. Can we have this in Xamarin Forms SDK or a way to add this using Renderer/ Dependancy service ? 
Below is the sample method from native Android documentation: 

`@Override
public void onAudioLevelUpdated(
        SubscriberKit subscriber, float audioLevel)
 {
    // Adjust an audio meter UI element based on the audioLevel value.
}
`

**Comment by AndreiMisiukevich** [comment]
Not for now) But if you wish, you may make a PR

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/Xamarin.Forms.Vonage
