### ISSUE TITLE
Add event for new stream subscriptions

### ISSUE THREAD

**Issue by Gaisuru** [AndreiMisiukevich/OpenTok-Xamarin.Forms#34]
I have an app where I have two views. I want to populate them based on the first and second id in the collection. I need to manually bind these IDs but I do not know when the CrossOpenTok.Current.StreamIdCollection object will be populated. I am force to do a while loop and check the collection. Having an event to let us know that a the collection changed would be very helpful.

**Comment by AndreiMisiukevich** [comment]
Hi!
StreamIdCollection is ObservalbeCollection

```CrossOpenTok.Current.StreamIdCollection.CollectionChanged += (s, e) => { }```

**Comment by Gaisuru** [comment]
@AndreiMisiukevich That doesn't work. None of those type of properties are accessible because of the protection level of StreamIdCollection. Try to reference that in your sample project.

**Comment by AndreiMisiukevich** [comment]
v 1.2.6

**Comment by AndreiMisiukevich** [comment]
Use StreamIdCollectionChanged event
