### ISSUE TITLE
OpenTokSubscriberView not working

### ISSUE THREAD

**Issue by DasVerma** [AndreiMisiukevich/OpenTok-Xamarin.Forms#35]
Hi, 

this is query
I implemented this plugin in my xamarin forms project, created account obtained key, session and token but OpenTokSubscriberView not showing anything. is there any specific configuration needed or else? or how subscriberview works

**Comment by AndreiMisiukevich** [comment]
Publisher - You
Subscriber - Any another participant in the chat

So, just join the same session from another device

**Comment by DasVerma** [comment]
So 
"CrossOpenTok.Current.TryStartSession()" this will start session as "Publisher" then How "Subscriber" will join session, is there any method for joining same session ?
I installed the app (xamarin forms - android) in two different device and from one device clicked "click to chat"
and "OnEndCall" throwing exception of object reference

**Comment by AndreiMisiukevich** [comment]
Run my sample app (with your keys) on two different devices and click try start session on both

**Comment by DasVerma** [comment]
Yes i tried with your sample, its crashing for the second device 
Case - Opened app with first device clicked "Click to Chat" working fine showing "publisher view" but with second device on click "Click to chat" its closing app.

**Comment by AndreiMisiukevich** [comment]
Any stack trace appreciated)

**Comment by AndreiMisiukevich** [comment]
check newest version
