### ISSUE TITLE
Screen sharing - not being picked up

### ISSUE THREAD

**Issue by byronCoetzee** [AndreiMisiukevich/OpenTok-Xamarin.Forms#38]
Hi Andrei,
I am coding a combined website and mobile app solution. its online-tutoring solution,

When I change from video share to screen share on the site the xamarin nuget solution does not pick up the change and re-subscribe.
if I change back to video share - it does re-subscribe. 
Can you include this?

Or is there a way I can react to an event where I see its now screen-share video and then re-initialise?

Weirdly, if I end the session and init it again then it subscribes to the screen share video.

in java script I do this

session.on('streamCreated', function(event)
            {
                console.log("New stream in the session: " + event.stream.streamId);
                console.log("New stream in the session: " + event.stream.videoType);

                if (event.stream.videoType == 'camera')
                {
                    var elem = document.getElementById("subscriber");
                    elem.style.display = "block";
                    var elem = document.getElementById("whiteboard");
                    elem.style.display = "none";
                    subscriber = Null = session.subscribe(event.stream, 'subscriber',
                    {
                        insertMode: 'append',
                        width: '100%',
                        height: '100%',
                    }, handleError);
                }
                else
                if (event.stream.videoType == 'screen')
                {
                    var elem = document.getElementById("subscriber");
                    elem.style.display = "none";
                    var elem = document.getElementById("whiteboard");
                    elem.style.display = "block";
                    subscriber = Null = session.subscribe(event.stream, 'whiteboard',
                    {
                        insertMode: 'append',
                        width: '100%',
                        height: '100%',
                    }, handleError);
                };
            }
        );

**Comment by AndreiMisiukevich** [comment]
Hi try 1.2.9 (will be available in 20-30 mins)

**Comment by byronCoetzee** [comment]
Hi Andrei,
thanks for help so far!
I upgraded to latest 1.2.9 across the project, but it still does not work. 
It seems to work when I exit the xamarin form and re-enter the chat, but when I just stay on the xamarin chat then the switch to screen is not picked up and re-subscribed.

Regards,
Byron

**Comment by AndreiMisiukevich** [comment]
@byronCoetzee is this event triggered?
https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Lib/Xamarin.Forms.OpenTok/Service/IOpenTokService.cs#L15

Can you check?

**Comment by byronCoetzee** [comment]
yes when I change to screen share I get two events though there. (is there anything specific you want printed out ?)
just this
[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs
[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs

but when i change to normal video share there is whole lot of them (this works)

[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs
[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs
10-26 11:48:25.263 E/Surface (10137): getSlotFromBufferLocked: unknown buffer: 0x0
[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs
[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs
[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs
[0:] **** OnCollectionChanged System.Collections.Specialized.NotifyCollectionChangedEventArgs
10-26 11:48:30.210 D/        (10137): HostConnection::get() New Host Connection established 0x784a1aeaac80, tid 10464
10-26 11:48:30.231 D/EGL_emulation(10137): eglCreateContext: 0x784a16a5f6c0: maj 2 min 0 rcv 2
10-26 11:48:30.243 D/EGL_emulation(10137): eglMakeCurrent: 0x784a16a5f6c0: ver 2 0 (tinfo 0x784a3a84a3c0)

**Comment by byronCoetzee** [comment]
Hi Andrei,
I think I fixed this from my side.
I noticed there were less events coming through and most especially, there was no "remove" action coming through. So I changed my web page javascript code to make a more emphatic signal that the video publishing was off, before publishing the screen video. Your package seems to like this 👍 
Thanks you so much for your help!!
