### ISSUE TITLE
Event when subscriber end session

### ISSUE THREAD

**Issue by mimunoz** [AndreiMisiukevich/OpenTok-Xamarin.Forms#4]
Hi Andrei! nice work porting Opentok library to Xamarin.Forms. I've been using a mix of native library to Xamarin.Android/Xamarin.iOS in Xamarin.Forms project. I've been testing this plugin but I miss the event when the other person ends the videocall, OnSessionEnded(). I'm trying to catch it in CrossOpenTok.Current.PropertyChanged += (sender, e) => {...} the combination when that happens, but it's not clear when the call is ended, because IsPublishingStarted and IsSessionStarted begins with value = false, and event updated more than twice before video call is ended. All of this is for manage the Navigation.PopAsync().

Could you have an idea of how to handle it?

Regards!

**Comment by AndreiMisiukevich** [comment]
![image](https://user-images.githubusercontent.com/10124814/59414413-22e73a00-8dca-11e9-8214-45110022d2e9.png)

Unfortunately i haven't handle it yet

**Comment by AndreiMisiukevich** [comment]
IsSubscriberConnected

**Comment by mthirukavi** [comment]
@mimunoz or @AndreiMisiukevich Can you please share your idea of showing "video paused" message to publisher when subscriber pauses the video and vice versa.

**Comment by AndreiMisiukevich** [comment]
@mthirukavi each view of OpenTokSubscriberView *(and even OpenTokePublisherView)* have **IsVideoViewRunning** bindable property.

https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Lib/Xamarin.Forms.OpenTok/OpenTokView.cs

For example, you can add a trigger or workaround with bindings 

Does it help?)
