### ISSUE TITLE
Screen share - is this possible in this package

### ISSUE THREAD

**Issue by byronCoetzee** [AndreiMisiukevich/OpenTok-Xamarin.Forms#40]
Hi Andrei,

is it possible to to switch to screen sharing in this package? 

If not can you put it in?

Regards
Byron

**Comment by AndreiMisiukevich** [comment]
Hi, I don't think it's supported now
Feel free to submit a PR with this feature

**Comment by AndreiMisiukevich** [comment]
implemented in 1.3.2
