### ISSUE TITLE
I can't end session in android even if I call "CrossOpenTok.Current.EndSession()". The stream is still running. 

### ISSUE THREAD

**Issue by AhmedTaha0** [AndreiMisiukevich/OpenTok-Xamarin.Forms#41]

**Comment by AndreiMisiukevich** [comment]
Would you like to debug this case?

**Comment by AhmedTaha0** [comment]
First thanks for your fast reply. I can't understand what you mean by debugging this case. After I call "CrossOpenTok.Current.EndSession()" and navigate back I can't hear the other participant however my "output console" in vs still show that the stream is still running i.e. there is still a process running in the background. Hint: I talking about sample project so do you have any explanation for what happening

**Comment by AndreiMisiukevich** [comment]
Under "debugging" I mean downloading this project with the sample, setting up your keys, and watching what happens in code)

https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Lib/Xamarin.Forms.OpenTok.Android/Service/PlatformOpenTokService.cs#L81


As you can see we clear everything possible. Disconnect from the session and then dispose it

**Comment by AhmedTaha0** [comment]
Yes I understand however I run and debug this project and setting up my keys and after "EndSession()" is called there is still a process running in "output console" in visual studio which means that there is a process running in the background as you see in the image. The process is only closed when I kill the app. 
![image](https://user-images.githubusercontent.com/54868016/102235239-ca32b900-3efa-11eb-8bf5-556add9d7e19.png)

**Comment by AndreiMisiukevich** [comment]
> Yes I understand however I run and debug this project and setting up my keys and after "EndSession()" is called there is still a process running in "output console" in visual studio which means that there is a process running in the background as you see in the image. The process is only closed when I kill the app.
> ![image](https://user-images.githubusercontent.com/54868016/102235239-ca32b900-3efa-11eb-8bf5-556add9d7e19.png)

It can be some process out of our control. This plugin uses another xamarin plugin that wraps native SDK :)
I am not sure I can fix it somehow.

**Comment by AhmedTaha0** [comment]
ok thanks for your support

**Comment by AndreiMisiukevich** [comment]
Closing this issue since it is not supposed to be fixed (Also, I am not sure this output is related to opentok at all)
If you have any idea how to fix it, feel free to submit a PR
