### ISSUE TITLE
Can I force video call to use "Media volume button control" instead of "Call volume button" in Android? 

### ISSUE THREAD

**Issue by AhmedTaha0** [AndreiMisiukevich/OpenTok-Xamarin.Forms#43]
I tried 2 approaches and **none of them work**

1) By setting "GetStreamVolume"  in "OnCreate" method
```
AudioManager audio = (AudioManager)GetSystemService(Context.AudioService); audio.GetStreamVolume(Android.Media.Stream.Music); 
```
2) Set "VolumeControlStream" 
```
 VolumeControlStream = Android.Media.Stream.Music;
```
Any help? please.

**Comment by AndreiMisiukevich** [comment]
Hello, I am not sure it's possible now.
At least I cannot find how to set audio level for iOS and Android (but found for Web)

**Comment by AhmedTaha0** [comment]
Thank you for your support and I'm sorry for replying late

**Comment by AhmedTaha0** [comment]
@AndreiMisiukevich  
I have another question. How to set accept ratio into "Fit" during video call in Vonage?

**Comment by AndreiMisiukevich** [comment]
> @AndreiMisiukevich
> I have another question. How to set accept ratio into "Fit" during video call in Vonage?

It's an enhancement and requires implementation

**Comment by AndreiMisiukevich** [comment]
@AhmedTaha0 use v.1.3.4
Set those props https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/blob/master/Lib/Xamarin.Forms.OpenTok/Service/IOpenTokService.cs#L23-L25

**Comment by AhmedTaha0** [comment]
I'm speechless for your quick support, Thank you
