### ISSUE TITLE
Xamarin.Vonage.Android is not compiling for Andriod-10 and above

### ISSUE THREAD

**Issue by Bhargav-1995** [AndreiMisiukevich/OpenTok-Xamarin.Forms#44]
Im using Xamarin.Opentok.Android -2.18.1, im able to create video call from my android app. When i tried to upgrade the app target version to 10, video call is not working.
We have developed a telemedicine app using Xamarin-4.8. The app is live in certain regions. we have built for both android and ios. we updated the app recently and uploaded on play store. a lot of customers who are on android 10 and 11 started complaining that the app is not working and compatible with their versions.
we did a thorough investigation to check why the app is not working for android 10.
Our findings are mentioned below :
1. We were using the old namespace Xamarin.Opentok.Android. we replaced this with Xamarin.Vonage.Android as the forums said that Xamarin.Opentok.Android is deprecated.
2.Its working up to android-9 version, when we change the version to android-10 we are facing "System.MissingFieldException: 'Field not found: int .Animation.btn_checkbox_to_checked_box_inner_merged_animation Due to: Could not find field in class' ".
3.When we remove the dependencies of Opentok we are able to compile the application for Android-10.
4.Our understanding is that the "PlatformOpenTokService.Init();" class in not getting initialized and hence it is allowing us to compile on Android-10.
5.We were able to compile up to [Android-9.](url
![WhatsApp Image 2021-04-06 at 14 59 27](https://user-images.githubusercontent.com/82077586/113815339-9cff6480-9790-11eb-9da6-8fee62364a22.jpeg)
)

**Comment by Bhargav-1995** [comment]
Please Provide sample solution for Xamrin.Vonage.Android

**Comment by AndreiMisiukevich** [comment]
Hi @Bhargav-1995 you created an issue in the wrong repository :)

Here is the right one: https://github.com/DreamTeamMobile/Xamarin.Opentok.Samples

CC @alexsorokoletov
