### ISSUE TITLE
Session Ended Event

### ISSUE THREAD

**Issue by ivanrlg** [AndreiMisiukevich/OpenTok-Xamarin.Forms#46]
Hello Andrei,

Is there the possibility of implementing an event that allows us to be notified when a session from the other end has ended session? something similar to this Session.StreamDropped event?

Best regards,

**Comment by AndreiMisiukevich** [comment]
Hi @ivanrlg please use ```StreamIdCollectionChanged``` for this purpose (It is triggered every time a new participant added or removed)
