### ISSUE TITLE
Error in Camera

### ISSUE THREAD

**Issue by ivanrlg** [AndreiMisiukevich/OpenTok-Xamarin.Forms#47]
Hello Andrei,

I'm using your nutget, at some point I made a call and ended it, then I tried to make another call a few minutes later and I saw that there were problems with the visualization of one of the cameras.

The question is, is there something that can be done on your project side or mine to prevent the following error:

```
com.opentok.android.Camera2VideoCapturer.initCamera
com.opentok.android.Camera2VideoCapturer$Camera2Exception: CAMERA_IN_USE (4): connectHelper:1607: Higher-priority client using camera, ID "1" currently unavailable
```

Open
Stack traces
```
com.opentok.android.Camera2VideoCapturer.initCamera
com.opentok.android.Camera2VideoCapturer.a
com.opentok.android.Camera2VideoCapturer.lambda$EOJ6zJ_KyEal1aLQznxfTJOPcJc
com.opentok.android.-$$Lambda$Camera2VideoCapturer$EOJ6zJ_KyEal1aLQznxfTJOPcJc.run
com.opentok.android.Camera2VideoCapturer$4.onClosed
android.hardware.camera2.impl.CameraDeviceImpl$5.run CameraDeviceImpl.java:215
android.os.Handler.handleCallback Handler.java:883
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:224
android.app.ActivityThread.main ActivityThread.java:7565
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:539
com.android.internal.os.ZygoteInit.main ZygoteInit.java:950
```

Best regards.

**Comment by AndreiMisiukevich** [comment]
Does it happen on all devices?
Don't you use your camera somewhere else?

**Comment by ivanrlg** [comment]
Hello, so far it has happened to me 1 time.

I was not using the camera elsewhere.

**Comment by AndreiMisiukevich** [comment]
I am not sure we can fix it then :( if we can't reproduce it

**Comment by AndreiMisiukevich** [comment]
it should be a crash inside opentok native library

**Comment by AndreiMisiukevich** [comment]
This package will be deprecated soon

I will publish a new package with dependency on Vonage packages. I will let you know :)  Transition will be smooth
https://github.com/AndreiMisiukevich/OpenTok-Xamarin.Forms/issues/48

**Comment by ivanrlg** [comment]
Hello Andrei, Ok. Thank you very much for your feedback. I will be pending thanks.

**Comment by AndreiMisiukevich** [comment]
https://github.com/AndreiMisiukevich/Xamarin.Forms.Vonage
