### ISSUE TITLE
KeyURL not found in config.cs file in the sample.

### ISSUE THREAD

**Issue by Nikitajain1121** [AndreiMisiukevich/OpenTok-Xamarin.Forms#7]
I have integrated the provided github solution, but there is not "Key URL" provided.
Please suggest from where I can get the key url for my project used in the below snippet:
 
 ```
 using (var client = new HttpClient())
            {
                try
                {
                    var resp = await client.GetAsync(Config.KeysUrl);
                    var json = await resp.Content.ReadAsStringAsync();
                    var keys = JsonConvert.DeserializeObject<Keys>(json);

                    CrossOpenTok.Current.ApiKey = keys.ApiKey;
                    CrossOpenTok.Current.SessionId = keys.SessionId;
                    CrossOpenTok.Current.UserToken = keys.Token;
                }
                catch
                {
                    await DisplayAlert(null, "MAKE SURE YOU SET API URL FOR RETRIEVING NECESSARY KEYS (Config.cs) OR YOU MAY HARDCODE THEM.", "GOT IT");
                }
```

**Comment by Mibuw** [comment]
You have to make an account on tokbox.com!

**Comment by AndreiMisiukevich** [comment]
yeah, it's true. Create account here https://tokbox.com/ and follow steps.
You will get Api key, test session id and user token.

**Comment by GorkaL** [comment]
Hello Andrei,

Is there any way to get the session and token automatically? How can I configure that Config.KeysUrl to get the info automatically?

**Comment by AndreiMisiukevich** [comment]
@GorkaL Hi, follow steps on tokbox.com. It's possible to deploy your own server to heroku and get keys from that server
