### ISSUE TITLE
Multiparty video chat

### ISSUE THREAD

**Issue by lh-rmyers** [AndreiMisiukevich/OpenTok-Xamarin.Forms#8]
I'm currently trying to use this library to start a multiparty video chat, but it's not quite working as expected. When the third user joins the session, he acts as a view only subscriber as opposed to a publisher. This means the first two users don't see or hear his stream, and he only sees the first users stream. Is there a method I'm missing to enable multiparty?

**Comment by AndreiMisiukevich** [comment]
Hi @lh-rmyers 
not sure it's possible to achieve for now with this library

**Comment by AndreiMisiukevich** [comment]
Do you use a trial account or not?

**Comment by lh-rmyers** [comment]
Well that's quite unfortunate that it may not be possible. I've already started a couple of weeks of development time, and this was a requirement (that I admittedly should have tested day one). I do have a trial account yes. Would that possibly be the difference?

**Comment by AndreiMisiukevich** [comment]
@lh-rmyers hm, but if you use a trial account, it means that you use the same UserToken for all three users. Maybe this is the reason, not sure.

**Comment by lh-rmyers** [comment]
@AndreiMisiukevich That's actually something I tested for to be sure. We are uniquely generating tokens on a per user basis already as we have implemented an API that uses the OpenTokSDK to generate the keys. I appreciate any tips you might have. I'll be continuing to investigate any possible solutions in the mean time.

**Comment by AndreiMisiukevich** [comment]
@lh-rmyers hmmm

@alexsorokoletov could you please help ?)

**Comment by alexsorokoletov** [comment]
Sure, @lh-rmyers OpenTok supports multiparty calls, so does Xamarin OpenTok SDK (iOS/Android).
We did a couple of apps doing just that.

>When the third user joins the session, he acts as a view only subscriber as opposed to a publisher

This part is determined by whatever you do after you join a session.
If you only subscribe then you only see and hear. 
If you publish your stream and other clients subscribe to _your stream_ then they can hear and see you.

So check whether you call `Publish` after joining the session and make sure all other clients subscribe to all streams or to your specific stream.

**Comment by lh-rmyers** [comment]
@alexsorokoletov Good to hear this is already supported! I'm still struggling in getting it working though. I don't want to ask for free support or anything, but if you have any examples on how to call Publish, I'm happy to use that as an example. As it is right now. I don't see a place in this example code to put it. There's a lot going on behind the scenes and I'm struggling to delve into it at the moment (some progress has been made though where I've been able to switch which user one of the clients sees, but still not seeing both). I'm trying to compare to the Java version of OpenTok [here](https://github.com/opentok/opentok-android-sdk-samples/blob/master/Simple-Multiparty/app/src/main/java/com/tokbox/android/tutorials/simple_multiparty/MainActivity.java#L235), but I'm still not quite there yet.

There is a "Session.Publish", but that code is contained behind the scenes on the "OnDidConnect", which isn't accessible from outside the library code. 

Is this something I will need to modify the library to do for my own needs instead of pulling this one in through NuGet?

Thanks again, I really do appreciate any help you might have time to give.

**Comment by AndreiMisiukevich** [comment]
@lh-rmyers I think, the best approach would be - download this project as source code, implement this feature and make PR :)

**Comment by lh-rmyers** [comment]
@AndreiMisiukevich Hey, I've been working on implementing this feature (so far in Android only, iOS will come when it's done), and I was wondering if I could get help on what I'm hoping is the last step. I've got it so that I can add each subscriber to the chat room, but I can only hear them, I don't see them for some reason. If you get a chance, could you take a look into what I might be doing wrong?

I'm dynamically adding subscribers through code, which I assume I'm missing something that will actually render it to the page.

**Comment by AndreiMisiukevich** [comment]
@lh-rmyers sorry, now I have extremely little time :( I will be more free in 1 month I think :(

**Comment by AndreiMisiukevich** [comment]
@lh-rmyers but if i have i chance to look, i will do it

**Comment by AndreiMisiukevich** [comment]
1.2.0
